export default {
    WELCOME_TITLE: 'Get things done with todo - Your Tasks',
    STARTED: 'Get started',
    MADE_BY_AUTHOR: 'Made by Bruce Tran in 2024',
    HAS_ACCOUNT: 'Already have an account?',
    NO_ACCOUNT: 'Dont have an account?',
    SIGN_IN: 'Sign In',
    SIGN_UP: 'Sign Up',
    WELCOME_ONBOARD: 'Welcome Onboard!',
    LET_START: 'Let\'s help you meet up your task',
    BACK: 'Back',
    WELCOME: 'Welcome',
    WELCOME_BACK: 'Welcome back!',
    ENTER_NAME: 'Enter your full name',
    ENTER_EMAIL: 'Enter your email',
    ENTER_PASSWORD: 'Enter your password',
    CREATE_PASSWORD: 'Create a password',
    CONFIRM_PASSWORD: 'Confirm your password',
    DOING_TASKS: 'Todo Tasks',
    ARCHIVED_TASKS: 'Archived Tasks',
    CREATE_TASK: 'Create new task today...',
    NO_TASK: 'You don\'t have any task here!',
    LOREMS: 'Lorem ipsum dolor sit amet, consectetur adipisicing. Maxime, tempore! Animi nemo aut atque, deleniti nihil dolorem repellendus.'
}